### PR TITLE
CMake modernisation

### PR DESCRIPTION
**Pull request by Johanmyst**
As requested by @yuleisui in [pull request #1305](https://github.com/SVF-tools/SVF/pull/1305) in the main SVF repository, this pull request updates the CMake scripts for the example project.

The changes in this request show how to include SVF when installed through the updated CMake script, and how the different build configuration variables can be accessed. I tested this using LLVM 15.0.7 (release build) and the most recent version of SVF.

### CODE REVIEW

**Comment by yuleisui** [comment]
@Johanmyst there is an error when trying to find_package(SVF). Could you please take a look: https://github.com/SVF-tools/SVF-example/actions/runs/7540713641/job/20525892923?pr=62#step:8:35

**Comment by Johanmyst** [comment]
> @Johanmyst there is an error when trying to find_package(SVF). Could you please take a look: https://github.com/SVF-tools/SVF-example/actions/runs/7540713641/job/20525892923?pr=62#step:8:35

That's because I wrote this as an example of how to use the modernised version (that I assumed would show how to use the SVF CMake package if it was installed), so when the CMake package wasn't installed this would fail. However, I've retrofitted the "official"/old approach into this update so now it should just use the old approach when the CMake package cannot be found.

**Comment by yuleisui** [comment]
> > @Johanmyst there is an error when trying to find_package(SVF). Could you please take a look: https://github.com/SVF-tools/SVF-example/actions/runs/7540713641/job/20525892923?pr=62#step:8:35
> 
> That's because I wrote this as an example of how to use the modernised version (that I assumed would show how to use the SVF CMake package if it was installed), so when the CMake package wasn't installed this would fail. However, I've retrofitted the "official"/old approach into this update so now it should just use the old approach when the CMake package cannot be found.

Yes, I noticed this. However, I also realize the old folder layout and npm should be improved and make the folder layout consistent with your installation mode.

**Comment by yuleisui** [comment]
@Johanmyst svf’s NPM is a direct copy of the release-build, if you could help fix SVF’s build by generating the same layout as your installation. We can have a compact and clean cmake here using the find_package way.

**Pull request merged**
